#!/bin/sh

source /etc/tizen-platform.conf

vconf_set_safemode()
{
	if [ -f $TZ_SYS_ETC/.safemode ]
	then
		vconftool set -t int memory/idle-screen/safemode "1" -i -f
	else
		vconftool set -t int memory/idle-screen/safemode "0" -i -f
	fi
}
vconf_set_safemode

echo -e "<2>[${_G}menu-daemon start${C_}]" > /dev/kmsg
$TZ_SYS_BIN/starter &
